language: objective-c
osx_image: xcode7.1
before_install:
  brew install carthage

script: ./build.sh

branches:
  only:
    - master

env:
- TARGET=WebDriverAgent SDK=iphonesimulator ACTION=build
- TARGET=XCTUITestRunner SDK=iphonesimulator ACTION=build-tests
- TARGET=XCTUITestRunner SDK=iphoneos ACTION=build-tests
